name: StaffMode
author: ItsMax123
main: Max\StaffMode\Main
version: 2.0.1
api: [3.0.0]

commands:
 staffmode:
  description: Puts you in staff mode.
  usage: "/staffmode"
  aliases: ["sm"]
  permission: staffmode.command.staffmode
 staffchat:
    description: Puts you in staff chat.
    usage: "/staffchat"
    aliases: [ "sc" ]
    permission: staffmode.staffchat
 report:
  description: Opens the report Interface.
  usage: "/report"
  permission: staffmode.command.report

permissions:
  staffmode.command.report:
    default: true
    description: Allows usage of the "/report" command.
  staffmode.bypass:
    default: op
    description: Allows usage of staffmode tools against other staff members.
  staffmode.*:
    default: op
    description: Allows usage of all staffmode features.
    children:
      staffmode.command.staffmode:
        default: op
        description: Allows usage of the "/staffmode" command.
      staffmode.staffchat:
        default: op
        description: Allows usage of the "/staffchat" command.
      staffmode.silent:
        default: op
        description: Allows player to join and leave the server with no broadcasted message.
      staffmode.tools.teleport:
        default: op
        description: Allows usage of the teleportation tool (compass) in staffmode.
      staffmode.tools.playerinfo:
        default: op
        description: Allows usage of the PlayerInfo tool (book) in staffmode.
      staffmode.tools.warn:
        default: op
        description: Allows usage of the warning tool (paper) in staffmode.
      staffmode.tools.freeze:
        default: op
        description: Allows usage of the freezing tool (ice block) in staffmode.
      staffmode.tools.mute:
        default: op
        description: Allows usage of the muting tool (gold hoe) in staffmode.
      staffmode.tools.kick:
        default: op
        description: Allows usage of the kicking tool (gold sword) in staffmode.
      staffmode.tools.ban:
        default: op
        description: Allows usage of the banning tool (gold axe) in staffmode.
      staffmode.tools.exit:
        default: true
        description: Allows usage of the exit tool (redstone torch) in staffmode.